apiVersion: v1
kind: Service
metadata:
  name: court-service
  namespace: courtmate-dev
spec:
  type: ClusterIP
  selector:
    app: court-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP